In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import accuracy_score

In [2]:
df = pd.read_csv(r'E:\Courses\Data Science\Data\6 - Machine Learning\7 - Ensemble\WA_Fn-UseC_-Telco-Customer-Churn.csv')

In [3]:
df.head(5)

customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1           No   
1  5575-GNVDE    Male              0      No         No      34          Yes   
2  3668-QPYBK    Male              0      No         No       2          Yes   
3  7795-CFOCW    Male              0      No         No      45           No   
4  9237-HQITU  Female              0      No         No       2          Yes   

      MultipleLines InternetService OnlineSecurity  ... DeviceProtection  \
0  No phone service             DSL             No  ...               No   
1                No             DSL            Yes  ...              Yes   
2                No             DSL            Yes  ...               No   
3  No phone service             DSL            Yes  ...              Yes   
4                No     Fiber optic             No  ...               No   

  TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \
0          No          No              No  Month-to-month              Yes   
1          No          No              No        One year               No   
2          No          No              No  Month-to-month              Yes   
3         Yes          No              No        One year               No   
4          No          No              No  Month-to-month              Yes   

               PaymentMethod MonthlyCharges  TotalCharges Churn  
0           Electronic check          29.85         29.85    No  
1               Mailed check          56.95        1889.5    No  
2               Mailed check          53.85        108.15   Yes  
3  Bank transfer (automatic)          42.30       1840.75    No  
4           Electronic check          70.70        151.65   Yes  

[5 rows x 21 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   customerID        7043 non-null   object 
 1   gender            7043 non-null   object 
 2   SeniorCitizen     7043 non-null   int64  
 3   Partner           7043 non-null   object 
 4   Dependents        7043 non-null   object 
 5   tenure            7043 non-null   int64  
 6   PhoneService      7043 non-null   object 
 7   MultipleLines     7043 non-null   object 
 8   InternetService   7043 non-null   object 
 9   OnlineSecurity    7043 non-null   object 
 10  OnlineBackup      7043 non-null   object 
 11  DeviceProtection  7043 non-null   object 
 12  TechSupport       7043 non-null   object 
 13  StreamingTV       7043 non-null   object 
 14  StreamingMovies   7043 non-null   object 
 15  Contract          7043 non-null   object 
 16  PaperlessBilling  7043 non-null   object 


In [5]:
df.TotalCharges = pd.to_numeric(df.TotalCharges, errors='coerce')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   customerID        7043 non-null   object 
 1   gender            7043 non-null   object 
 2   SeniorCitizen     7043 non-null   int64  
 3   Partner           7043 non-null   object 
 4   Dependents        7043 non-null   object 
 5   tenure            7043 non-null   int64  
 6   PhoneService      7043 non-null   object 
 7   MultipleLines     7043 non-null   object 
 8   InternetService   7043 non-null   object 
 9   OnlineSecurity    7043 non-null   object 
 10  OnlineBackup      7043 non-null   object 
 11  DeviceProtection  7043 non-null   object 
 12  TechSupport       7043 non-null   object 
 13  StreamingTV       7043 non-null   object 
 14  StreamingMovies   7043 non-null   object 
 15  Contract          7043 non-null   object 
 16  PaperlessBilling  7043 non-null   object 


In [7]:
df.dropna(how='any', inplace=True)

In [8]:
len(df)

7032

In [9]:
df.head(5)

customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1           No   
1  5575-GNVDE    Male              0      No         No      34          Yes   
2  3668-QPYBK    Male              0      No         No       2          Yes   
3  7795-CFOCW    Male              0      No         No      45           No   
4  9237-HQITU  Female              0      No         No       2          Yes   

      MultipleLines InternetService OnlineSecurity  ... DeviceProtection  \
0  No phone service             DSL             No  ...               No   
1                No             DSL            Yes  ...              Yes   
2                No             DSL            Yes  ...               No   
3  No phone service             DSL            Yes  ...              Yes   
4                No     Fiber optic             No  ...               No   

  TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \
0          No          No              No  Month-to-month              Yes   
1          No          No              No        One year               No   
2          No          No              No  Month-to-month              Yes   
3         Yes          No              No        One year               No   
4          No          No              No  Month-to-month              Yes   

               PaymentMethod MonthlyCharges  TotalCharges  Churn  
0           Electronic check          29.85         29.85     No  
1               Mailed check          56.95       1889.50     No  
2               Mailed check          53.85        108.15    Yes  
3  Bank transfer (automatic)          42.30       1840.75     No  
4           Electronic check          70.70        151.65    Yes  

[5 rows x 21 columns]

In [10]:
df.Churn.value_counts()/len(df)*100

Churn
No     73.421502
Yes    26.578498
Name: count, dtype: float64

In [11]:
X=df.drop(['customerID', 'Churn'], axis=1)

In [12]:
y=df.Churn.values

In [13]:
X

gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0     Female              0     Yes         No       1           No   
1       Male              0      No         No      34          Yes   
2       Male              0      No         No       2          Yes   
3       Male              0      No         No      45           No   
4     Female              0      No         No       2          Yes   
...      ...            ...     ...        ...     ...          ...   
7038    Male              0     Yes        Yes      24          Yes   
7039  Female              0     Yes        Yes      72          Yes   
7040  Female              0     Yes        Yes      11           No   
7041    Male              1     Yes         No       4          Yes   
7042    Male              0      No         No      66          Yes   

         MultipleLines InternetService OnlineSecurity OnlineBackup  \
0     No phone service             DSL             No          Yes   
1                   No             DSL            Yes           No   
2                   No             DSL            Yes          Yes   
3     No phone service             DSL            Yes           No   
4                   No     Fiber optic             No           No   
...                ...             ...            ...          ...   
7038               Yes             DSL            Yes           No   
7039               Yes     Fiber optic             No          Yes   
7040  No phone service             DSL            Yes           No   
7041               Yes     Fiber optic             No           No   
7042                No     Fiber optic            Yes           No   

     DeviceProtection TechSupport StreamingTV StreamingMovies        Contract  \
0                  No          No          No              No  Month-to-month   
1                 Yes          No          No              No        One year   
2                  No          No          No              No  Month-to-month   
3                 Yes         Yes          No              No        One year   
4                  No          No          No              No  Month-to-month   
...               ...         ...         ...             ...             ...   
7038              Yes         Yes         Yes             Yes        One year   
7039              Yes          No         Yes             Yes        One year   
7040               No          No          No              No  Month-to-month   
7041               No          No          No              No  Month-to-month   
7042              Yes         Yes         Yes             Yes        Two year   

     PaperlessBilling              PaymentMethod  MonthlyCharges  TotalCharges  
0                 Yes           Electronic check           29.85         29.85  
1                  No               Mailed check           56.95       1889.50  
2                 Yes               Mailed check           53.85        108.15  
3                  No  Bank transfer (automatic)           42.30       1840.75  
4                 Yes           Electronic check           70.70        151.65  
...               ...                        ...             ...           ...  
7038              Yes               Mailed check           84.80       1990.50  
7039              Yes    Credit card (automatic)          103.20       7362.90  
7040              Yes           Electronic check           29.60        346.45  
7041              Yes               Mailed check           74.40        306.60  
7042              Yes  Bank transfer (automatic)          105.65       6844.50  

[7032 rows x 19 columns]

In [14]:
y

array(['No', 'No', 'Yes', ..., 'No', 'Yes', 'No'],
      shape=(7032,), dtype=object)

In [15]:
X.columns

Index(['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure',
       'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity',
       'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
       'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod',
       'MonthlyCharges', 'TotalCharges'],
      dtype='object')

In [16]:
# Convert categorical features to numericals --> Feature Encoding --> Dummy Encoding

X = pd.get_dummies(X, columns=['gender', 'Partner', 'Dependents',
       'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity',
       'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
       'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod'], drop_first=True)

In [17]:
X.head(1)

SeniorCitizen  tenure  MonthlyCharges  TotalCharges  gender_Male  \
0              0       1           29.85         29.85        False   

   Partner_Yes  Dependents_Yes  PhoneService_Yes  \
0         True           False             False   

   MultipleLines_No phone service  MultipleLines_Yes  ...  \
0                            True              False  ...   

   StreamingTV_No internet service  StreamingTV_Yes  \
0                            False            False   

   StreamingMovies_No internet service  StreamingMovies_Yes  \
0                                False                False   

   Contract_One year  Contract_Two year  PaperlessBilling_Yes  \
0              False              False                  True   

   PaymentMethod_Credit card (automatic)  PaymentMethod_Electronic check  \
0                                  False                            True   

   PaymentMethod_Mailed check  
0                       False  

[1 rows x 30 columns]

In [18]:
# Splitting the data into training & test

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.25)

In [19]:
len(X_train)

5274

In [20]:
len(X_test)

1758

In [21]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train_sc = sc.fit_transform(X_train)
X_test_sc = sc.transform(X_test)

In [22]:
X_train_sc

array([[-0.43648504, -1.07584108,  0.69150528, ..., -0.52659933,
         1.40760271, -0.54535949],
       [-0.43648504, -1.28039897,  0.35666621, ..., -0.52659933,
         1.40760271, -0.54535949],
       [-0.43648504, -0.74854846,  0.06680552, ...,  1.89897697,
        -0.71042773, -0.54535949],
       ...,
       [-0.43648504, -1.19857582, -1.16593534, ..., -0.52659933,
         1.40760271, -0.54535949],
       [-0.43648504, -0.2985211 ,  0.21173587, ..., -0.52659933,
        -0.71042773,  1.83365288],
       [-0.43648504,  1.17429572,  0.99136117, ..., -0.52659933,
        -0.71042773, -0.54535949]], shape=(5274, 30))

In [23]:
X_test_sc

array([[ 2.29102928, -1.07584108, -0.67283899, ..., -0.52659933,
         1.40760271, -0.54535949],
       [-0.43648504, -1.11675266, -1.28920942, ..., -0.52659933,
        -0.71042773, -0.54535949],
       [ 2.29102928, -0.05305163,  0.8281063 , ..., -0.52659933,
         1.40760271, -0.54535949],
       ...,
       [-0.43648504,  1.46067677, -0.01648778, ..., -0.52659933,
        -0.71042773, -0.54535949],
       [-0.43648504, -0.78946003,  0.98303184, ..., -0.52659933,
         1.40760271, -0.54535949],
       [-0.43648504,  1.29703045,  1.68269557, ..., -0.52659933,
        -0.71042773, -0.54535949]], shape=(1758, 30))

#### kNN Classifier

In [24]:
# Call the kNN Classifier
from sklearn.neighbors import KNeighborsClassifier

# Initiating the classifier
model = KNeighborsClassifier()

# Passing the data to classifier
model.fit(X_train_sc, y_train)

KNeighborsClassifier()

In [25]:
y_pred = model.predict(X_test_sc)

In [26]:
y_pred

array(['Yes', 'No', 'Yes', ..., 'No', 'Yes', 'No'],
      shape=(1758,), dtype=object)

In [27]:
y_test

array(['No', 'Yes', 'No', ..., 'No', 'Yes', 'No'],
      shape=(1758,), dtype=object)

In [28]:
# Classification metrics = to check how the model is behaving

from sklearn.metrics import accuracy_score

print(accuracy_score(y_test,y_pred)*100)

75.65415244596132


#### New data prediction

In [29]:
X_test_sc

array([[ 2.29102928, -1.07584108, -0.67283899, ..., -0.52659933,
         1.40760271, -0.54535949],
       [-0.43648504, -1.11675266, -1.28920942, ..., -0.52659933,
        -0.71042773, -0.54535949],
       [ 2.29102928, -0.05305163,  0.8281063 , ..., -0.52659933,
         1.40760271, -0.54535949],
       ...,
       [-0.43648504,  1.46067677, -0.01648778, ..., -0.52659933,
        -0.71042773, -0.54535949],
       [-0.43648504, -0.78946003,  0.98303184, ..., -0.52659933,
         1.40760271, -0.54535949],
       [-0.43648504,  1.29703045,  1.68269557, ..., -0.52659933,
        -0.71042773, -0.54535949]], shape=(1758, 30))

In [30]:
X_test.columns

Index(['SeniorCitizen', 'tenure', 'MonthlyCharges', 'TotalCharges',
       'gender_Male', 'Partner_Yes', 'Dependents_Yes', 'PhoneService_Yes',
       'MultipleLines_No phone service', 'MultipleLines_Yes',
       'InternetService_Fiber optic', 'InternetService_No',
       'OnlineSecurity_No internet service', 'OnlineSecurity_Yes',
       'OnlineBackup_No internet service', 'OnlineBackup_Yes',
       'DeviceProtection_No internet service', 'DeviceProtection_Yes',
       'TechSupport_No internet service', 'TechSupport_Yes',
       'StreamingTV_No internet service', 'StreamingTV_Yes',
       'StreamingMovies_No internet service', 'StreamingMovies_Yes',
       'Contract_One year', 'Contract_Two year', 'PaperlessBilling_Yes',
       'PaymentMethod_Credit card (automatic)',
       'PaymentMethod_Electronic check', 'PaymentMethod_Mailed check'],
      dtype='object')

In [31]:
data = [[0, 2, 87, 178, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1]]

In [32]:
data_sc = sc.transform(data)

single = model.predict(data_sc)

print(single)

['Yes']


E:\Courses\Data Science\.venv\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [33]:
data_sc = sc.transform(data)

single = model.predict_proba(data_sc)

print(single)

[[0.2 0.8]]


E:\Courses\Data Science\.venv\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


#### Decision Tree Classifier

In [34]:
# Call the DT Classifier
from sklearn.tree import DecisionTreeClassifier

# Initiating the classifier
model_dt = DecisionTreeClassifier()

# Passing the data to classifier
model_dt.fit(X_train_sc, y_train)

DecisionTreeClassifier()

In [35]:
y_pred_dt = model_dt.predict(X_test_sc)

In [36]:
# Classification metrics = to check how the model is behaving

from sklearn.metrics import accuracy_score

print(accuracy_score(y_test,y_pred_dt)*100)

72.63936291240046


#### Random Forest Classifier

In [37]:
# Call the Random Forest Classifier
from sklearn.ensemble import RandomForestClassifier

# Initiating the classifier
model_rf = RandomForestClassifier(n_estimators=200)

# Passing the data to classifier
model_rf.fit(X_train_sc, y_train)

RandomForestClassifier(n_estimators=200)

In [38]:
y_pred_rf = model_rf.predict(X_test_sc)

In [39]:
# Classification metrics = to check how the model is behaving

from sklearn.metrics import accuracy_score

print(accuracy_score(y_test,y_pred_rf)*100)

79.92036405005688


In [40]:
from sklearn.metrics import classification_report

knn_report = classification_report(y_test, y_pred)
dt_report = classification_report(y_test, y_pred_dt)
rf_report = classification_report(y_test, y_pred_rf)

In [41]:
print('knn report', knn_report)

knn report               precision    recall  f1-score   support

          No       0.83      0.85      0.84      1285
         Yes       0.55      0.51      0.53       473

    accuracy                           0.76      1758
   macro avg       0.69      0.68      0.68      1758
weighted avg       0.75      0.76      0.75      1758



In [42]:
print('dt report', dt_report)

dt report               precision    recall  f1-score   support

          No       0.82      0.81      0.81      1285
         Yes       0.49      0.50      0.50       473

    accuracy                           0.73      1758
   macro avg       0.65      0.66      0.65      1758
weighted avg       0.73      0.73      0.73      1758



In [43]:
print('rf report', rf_report)

rf report               precision    recall  f1-score   support

          No       0.83      0.90      0.87      1285
         Yes       0.66      0.51      0.58       473

    accuracy                           0.80      1758
   macro avg       0.75      0.71      0.72      1758
weighted avg       0.79      0.80      0.79      1758



#### Naive Bayes Classifier

In [44]:
# Call the Random Forest Classifier
from sklearn.naive_bayes import BernoulliNB

# Initiating the classifier
model_nb = BernoulliNB()

# Passing the data to classifier
model_nb.fit(X_train_sc, y_train)

# Predictions
y_pred_nb = model_nb.predict(X_test_sc)

# Accuracy Score
print(accuracy_score(y_test,y_pred_nb)*100)

73.43572241183163


#### SVM Classifier

In [45]:
# Call the Random Forest Classifier
from sklearn.svm import SVC

# Initiating the classifier
model_svc = SVC()

# Passing the data to classifier
model_svc.fit(X_train_sc, y_train)

# Predictions
y_pred_svc = model_svc.predict(X_test_sc)

# Accuracy Score
print(accuracy_score(y_test,y_pred_svc)*100)

80.14789533560864


In [46]:
svc_report = classification_report(y_test, y_pred_svc)
print(svc_report)

              precision    recall  f1-score   support

          No       0.83      0.91      0.87      1285
         Yes       0.68      0.50      0.57       473

    accuracy                           0.80      1758
   macro avg       0.76      0.71      0.72      1758
weighted avg       0.79      0.80      0.79      1758



#### Logistic Regression Classifier

In [47]:
# Call the Random Forest Classifier
from sklearn.linear_model import LogisticRegression

# Initiating the classifier
model_lr = LogisticRegression()

# Passing the data to classifier
model_lr.fit(X_train_sc, y_train)

# Predictions
y_pred_lr = model_lr.predict(X_test_sc)

# Accuracy Score
print(accuracy_score(y_test,y_pred_lr)*100)

81.45620022753128


In [48]:
lr_report = classification_report(y_test, y_pred_lr)
print(lr_report)

              precision    recall  f1-score   support

          No       0.85      0.90      0.88      1285
         Yes       0.69      0.57      0.62       473

    accuracy                           0.81      1758
   macro avg       0.77      0.74      0.75      1758
weighted avg       0.81      0.81      0.81      1758



### **Ensemble Learning**

#### **Adaboost**

In [ ]:
# Call the AdaBoost Classifier
from sklearn.ensemble import AdaBoostClassifier

# Initiating the classifier
model_ada = AdaBoostClassifier(n_estimators=200)

# Passing the data to classifier
model_ada.fit(X_train_sc, y_train)

# Predictions
y_pred_ada = model_ada.predict(X_test_sc)

print("Accuracy of AdaBoost: ", accuracy_score(y_test, y_pred_ada))

Accuracy of AdaBoost:  0.8003412969283277


#### **Gradient Boost**

In [ ]:
# Call the GB Classifier
from sklearn.ensemble import GradientBoostingClassifier

# Initiating the classifier
model_gb = GradientBoostingClassifier(n_estimators=200)

# Passing the data to classifier
model_gb.fit(X_train_sc, y_train)

# Predictions
y_pred_gb = model_gb.predict(X_test_sc)

print("Accuracy of GB: ", accuracy_score(y_test, y_pred_gb))

Accuracy of GB:  0.8003412969283277


#### **XG Boost**

In [124]:
y[y=='No'] = 0
y[y=='Yes'] = 1

In [125]:
y

array([0, 0, 1, ..., 0, 1, 0], dtype=object)

In [126]:
# Splitting the data into training & test

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.25)

# Converting data to integer
y_test = y_test.astype(int)
y_train = y_train.astype(int)

# Feature Scaling
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train_sc = sc.fit_transform(X_train)
X_test_sc = sc.transform(X_test)

In [139]:
# Call the XGB Classifier
from xgboost import XGBClassifier

# Initiating the classifier
model_xgb = XGBClassifier(n_estimators=100, max_depth=4,learning_rate=0.1)

# Passing the data to classifier
model_xgb.fit(X_train_sc, y_train)

# Predictions
y_pred_xgb = model_xgb.predict(X_test_sc)

In [140]:
print("Accuracy of XGB: ", accuracy_score(y_test, y_pred_xgb))

Accuracy of XGB:  0.8043230944254836
